services:
  api:
    container_name: "api"
    volumes:
      - .:/workspace
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspace/scripts
    command: bash -c "./run.sh"
    ports:
      - 8000:8000
